-- OBD-II DTC lookup seed data
-- Common P0xxx codes per SAE J2012 standard. Prioritizes codes relevant to
-- tuned/modified vehicles: misfires, fuel trims, boost, knock, O2 sensors.

INSERT INTO public.dtc_lookup (code, description, system, severity_hint, common_causes) VALUES
  ('P0101', 'Mass Air Flow Circuit Range/Performance', 'fuel_air_metering', 'warning', 'Dirty or failing MAF sensor, vacuum leak, aftermarket intake'),
  ('P0102', 'Mass Air Flow Circuit Low Input', 'fuel_air_metering', 'warning', 'MAF sensor wiring fault, disconnected connector'),
  ('P0103', 'Mass Air Flow Circuit High Input', 'fuel_air_metering', 'warning', 'MAF sensor fault, wiring short'),
  ('P0106', 'Manifold Absolute Pressure Circuit Range/Performance', 'fuel_air_metering', 'warning', 'MAP sensor fault, boost leak, vacuum leak'),
  ('P0107', 'Manifold Absolute Pressure Circuit Low Input', 'fuel_air_metering', 'warning', 'MAP sensor wiring fault'),
  ('P0108', 'Manifold Absolute Pressure Circuit High Input', 'fuel_air_metering', 'warning', 'MAP sensor fault, boost overpressure'),
  ('P0111', 'Intake Air Temperature Circuit Range/Performance', 'fuel_air_metering', 'info', 'IAT sensor fault, aftermarket intake placement'),
  ('P0113', 'Intake Air Temperature Circuit High Input', 'fuel_air_metering', 'info', 'IAT sensor wiring fault'),
  ('P0116', 'Engine Coolant Temperature Circuit Range/Performance', 'fuel_air_metering', 'warning', 'ECT sensor fault, thermostat issue'),
  ('P0117', 'Engine Coolant Temperature Circuit Low Input', 'fuel_air_metering', 'warning', 'ECT sensor wiring short'),
  ('P0118', 'Engine Coolant Temperature Circuit High Input', 'fuel_air_metering', 'critical', 'ECT sensor fault, cooling system failure'),
  ('P0120', 'Throttle Position Sensor Circuit Malfunction', 'fuel_air_metering', 'warning', 'TPS wiring fault, aftermarket throttle body'),
  ('P0125', 'Insufficient Coolant Temperature for Closed Loop', 'fuel_air_metering', 'info', 'Thermostat stuck open, short trips only'),
  ('P0128', 'Coolant Thermostat Below Regulating Temperature', 'fuel_air_metering', 'warning', 'Failed thermostat, ECT sensor fault'),
  ('P0130', 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)', 'emissions', 'warning', 'Failed O2 sensor, wiring fault, exhaust leak'),
  ('P0131', 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)', 'emissions', 'warning', 'O2 sensor fault, lean condition'),
  ('P0132', 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)', 'emissions', 'warning', 'O2 sensor fault, rich condition, fuel pressure issue'),
  ('P0133', 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)', 'emissions', 'info', 'Aging O2 sensor, contamination'),
  ('P0135', 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)', 'emissions', 'warning', 'O2 sensor heater circuit fault'),
  ('P0170', 'Fuel Trim Malfunction (Bank 1)', 'fuel_air_metering', 'warning', 'Vacuum leak, injector issue, tune fuel map error'),
  ('P0171', 'System Too Lean (Bank 1)', 'fuel_air_metering', 'warning', 'Vacuum leak, weak fuel pump, MAF calibration, aftermarket intake'),
  ('P0172', 'System Too Rich (Bank 1)', 'fuel_air_metering', 'warning', 'Leaking injector, MAF fault, tune fuel map too rich'),
  ('P0174', 'System Too Lean (Bank 2)', 'fuel_air_metering', 'warning', 'Vacuum leak, weak fuel pump, bank 2 specific issue'),
  ('P0175', 'System Too Rich (Bank 2)', 'fuel_air_metering', 'warning', 'Leaking injector, bank 2 specific issue'),
  ('P0201', 'Injector Circuit Malfunction Cylinder 1', 'ignition', 'warning', 'Failed injector, wiring fault'),
  ('P0230', 'Fuel Pump Primary Circuit Malfunction', 'fuel_air_metering', 'critical', 'Fuel pump relay, wiring fault, upgraded pump wiring issue'),
  ('P0234', 'Turbocharger/Supercharger Overboost Condition', 'turbo_boost', 'critical', 'Wastegate stuck, boost controller fault, tune overboost'),
  ('P0236', 'Turbocharger Boost Sensor A Circuit Range/Performance', 'turbo_boost', 'warning', 'Boost sensor fault, boost leak, aftermarket boost controller'),
  ('P0299', 'Turbocharger/Supercharger Underboost Condition', 'turbo_boost', 'warning', 'Boost leak, wastegate stuck open, failing turbo'),
  ('P0300', 'Random/Multiple Cylinder Misfire Detected', 'ignition', 'critical', 'Worn plugs, ignition coil, lean/rich condition, tune issue'),
  ('P0301', 'Cylinder 1 Misfire Detected', 'ignition', 'warning', 'Faulty spark plug, coil, injector on cylinder 1'),
  ('P0302', 'Cylinder 2 Misfire Detected', 'ignition', 'warning', 'Faulty spark plug, coil, injector on cylinder 2'),
  ('P0303', 'Cylinder 3 Misfire Detected', 'ignition', 'warning', 'Faulty spark plug, coil, injector on cylinder 3'),
  ('P0304', 'Cylinder 4 Misfire Detected', 'ignition', 'warning', 'Faulty spark plug, coil, injector on cylinder 4'),
  ('P0325', 'Knock Sensor 1 Circuit Malfunction', 'ignition', 'warning', 'Knock sensor fault, wiring issue'),
  ('P0326', 'Knock Sensor 1 Circuit Range/Performance', 'ignition', 'critical', 'Excessive knock, tune too aggressive, low octane fuel, high boost'),
  ('P0335', 'Crankshaft Position Sensor Circuit Malfunction', 'ignition', 'critical', 'Failed CKP sensor, wiring fault, timing issue'),
  ('P0340', 'Camshaft Position Sensor Circuit Malfunction', 'ignition', 'warning', 'Failed CMP sensor, timing chain/belt issue'),
  ('P0401', 'Exhaust Gas Recirculation Flow Insufficient', 'emissions', 'info', 'EGR valve stuck, blocked passage'),
  ('P0420', 'Catalyst System Efficiency Below Threshold (Bank 1)', 'emissions', 'info', 'Aging catalytic converter, aftermarket exhaust, O2 sensor placement'),
  ('P0430', 'Catalyst System Efficiency Below Threshold (Bank 2)', 'emissions', 'info', 'Aging catalytic converter, bank 2 specific'),
  ('P0442', 'Evaporative Emission System Leak Detected (Small)', 'emissions', 'info', 'Loose gas cap, small EVAP leak'),
  ('P0455', 'Evaporative Emission System Leak Detected (Large)', 'emissions', 'info', 'Missing/loose gas cap, large EVAP leak'),
  ('P0500', 'Vehicle Speed Sensor Malfunction', 'vehicle_speed', 'warning', 'VSS fault, wiring issue'),
  ('P0505', 'Idle Control System Malfunction', 'fuel_air_metering', 'warning', 'Dirty throttle body, IAC valve fault'),
  ('P0562', 'System Voltage Low', 'computer_output', 'warning', 'Weak battery, alternator fault, wiring'),
  ('P0563', 'System Voltage High', 'computer_output', 'warning', 'Alternator overcharging, regulator fault'),
  ('P0601', 'Internal Control Module Memory Check Sum Error', 'computer_output', 'critical', 'ECU fault, corrupted tune flash'),
  ('P0606', 'ECM/PCM Processor Fault', 'computer_output', 'critical', 'ECU hardware fault, failed tune flash'),
  ('P0700', 'Transmission Control System Malfunction', 'transmission', 'warning', 'TCM fault, see transmission-specific codes'),
  ('P0715', 'Input/Turbine Speed Sensor Circuit Malfunction', 'transmission', 'warning', 'Turbine speed sensor fault'),
  ('P0720', 'Output Speed Sensor Circuit Malfunction', 'transmission', 'warning', 'Output speed sensor fault')
ON CONFLICT (code) DO UPDATE SET
  description = EXCLUDED.description,
  system = EXCLUDED.system,
  severity_hint = EXCLUDED.severity_hint,
  common_causes = EXCLUDED.common_causes;
